name: "Zipper Action"
description: "An action to zip the codebase and generate an artifact"
author: "revit2005@gmail.com"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
