name: Zipper workflow
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Workflow to zip the codebase and generate an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Zip codebase
        run: zip -r codebase.zip .
      - name: Upload codebase artifact
        uses: actions/upload-artifact@v2
        with:
          name: Codebase Artifact
          path: ./codebase.zip
